version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 3002:3002
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
