version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3001:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    depends_on:
      - api
